### ISSUE TITLE
Subsink uses CommonJS modules, which throws a warning when using Angular 10

### ISSUE THREAD

**Issue by elliotleelewis** [wardbell/subsink#11]
To remove the warning, we should be including an ESModule compile of the package too.

Here's some extra info: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by emiliovmq** [comment]
Yep, I'm having the same warning from ng 10 - WARNING in C:\Work\Src\angular\sample-projects\projects\ShoppingRecipes\src\app\header\header.component.ts depends on SubSink. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Any idea on when the change is gonna be implemented?

**Comment by brantsrasmus** [comment]
+1 Would be great if this could be implemented

**Comment by George35mk** [comment]
One solution is to include this in your `angular.json`

``` json
"architect" : {
    "build" : {
        "options" : {
            "allowedCommonJsDependencies": [
                "subsink"
            ]
        }
    }
}
```

**Comment by axell9641** [comment]
Yep I keep getting this warning since I moved to Angular 10 :'(

**Comment by stehag** [comment]
+1 for getting this fixed
