### ISSUE TITLE
Just a question: what is benefit against bare Subscription?

### ISSUE THREAD

**Issue by stasberkov** [wardbell/subsink#5]
Without SubSink you can do
```
subscription = new Subscription();
...
this.subscription.add(subs1$.subscribe(...));
this.subscription.add(subs2$.subscribe(...));
...
this.subscription.unsubscribe();
```
Can SubSink do it better?

**Comment by mailok** [comment]
@stasberkov Good question hahaha!!

**Comment by TheSegfault** [comment]
this.subscription.sink is a lot more stylish you have to admit !

**Comment by stefan-karlsson** [comment]
We use a base class for all our components. 
The base class have a protected ngUnsubscribe$ subject that is getting unsubscribed onDestroy.

When we have this we can use the RXJS pipe `takaUntil(this.ngUnscubscribe$)`

**Comment by jukestar** [comment]
There is a problem with adding to a subscription, where one subscription could "unsubscribe" another. https://github.com/ReactiveX/rxjs/issues/2769#issuecomment-345636477

**Comment by schuchard** [comment]
This was discussed at length in #1. I agree with the response from @wardbell 
> Use it if you like it. Ignore it if you don't. Cheers to all.
